# Generated by Django 5.1.7 on 2025-08-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_mouvementstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='MouvementStock',
        ),
    ]
